title: Francis Koh
logo: /assets/img/headshot.png
description: Data detective by day, problem-solver by trade—turning messy data into actionable insights with SQL, automation, and a touch of magic.
show_downloads: true
theme: jekyll-theme-minimal
